CREATE DATABASE gov;

USE gov;

CREATE TABLE usuario(
    USU_ID INT NOT NULL AUTO INCREMENT PRIMARY KEY,
    /* TO DO VERIFICAR VALIDADOR DE CPF PARA EVITAR ERROS DO USUARIO */
    USU_CPF VARCHAR(30) NOT NULL,
    USU_SENHA VARCHAR(50) NOT NULL
)